apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-kuber
spec:
  selector:
    matchLabels:
      app: go-kuber
  template:
    metadata:
      labels:
        app: go-kuber
    spec:
      containers:
      - name: go-kuber
        image: ghcr.io/avinal/go-kuber:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
